### ISSUE TITLE
CVSS vector string with Environmental metric group is not supported

### ISSUE THREAD

**Issue by minamo7sen** [stevespringett/cvss-calculator#66]
Hello,

The official CVSS v3.0 specification includes Environmental metric group, while the library does not support that.

Example code:
```java
String vectorWithEnvMetric = "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L/E:U/RL:O/RC:R/CR:L/IR:M/AR:M/MAV:N/MAC:L/MPR:N/MUI:N/MS:U/MC:N/MI:N/MA:N";
Cvss cvss = Cvss.fromVector(vectorWithEnvMetric);
Score score = cvss.calculateScore();
System.out.println(score.getEnvironmentalScore()); // 0.0 (should be 5.8)

```

Reference:
https://www.first.org/cvss/v3.0/specification-document#Environmental-Metrics

Expected result using the official CVSS calculator:
https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L/E:U/RL:O/RC:R/CR:L/IR:M/AR:M/MAV:N/MAC:L/MPR:N/MUI:N/MS:U/MC:L/MI:L/MA:L

**Comment by stevespringett** [comment]
temporal and environmental metrics are not currently supported. Pull requests are welcome.

**Comment by sschuberth** [comment]
Does https://github.com/stevespringett/cvss-calculator/pull/17 actually implement environmental metrics?

**Comment by sschuberth** [comment]
> Didn't #89 actually implement environmental metrics?

@stevespringett or @nscuro can you tell?

**Comment by minamo7sen** [comment]
Hello,

I just checked version 1.4.3, CVSS v3.1 with temporal & environmental metrics works fine.

I'll close this issue, thanks for your nice work.
